Добавляет стили
htmlacademy-htmlcss/1852279-sedona-35 pull request #6
Opened 2022-10-19 17:16 UTC by uk-ka

2022-10-28 11:24 UTC, maxzbest requested changes

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    color: black;
Стремимся к однородности и консистентности в коде, поэтому стараемся не юзать такие цвета

Поменяй на #000 и давай сразу все цвета вынесем в css-переменные

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    color: black;
Лишнее свойство, т.к. по умолчанию наследует от родителя такое же значение

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    background-color: white;
Лишнее свойство, т.к. по умолчанию наследует от родителя такое же значение

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    background-color: white;
Лишнее свойство, если убрать ничего не поменяется

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +.button {
Стили есть, а кому они адресованы?) Не нашёл в разметке кому этот класс прописан

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    color: #ffffff;
Когда все буквы или цифры одинаковые, то пишем в сокращённой аннотации #fff

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> + .button-email {
Не нашёл в разметке кому этот класс прописан

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    font-weight: 700;
Лишнее свойство, ничего не меняет (font-weight наследуется от h3 и совпадает с установленным значением)

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    background-color: rgba(131, 179, 211, 0.2);
Все цвета в формате hex храним, загугли калькулятор цвета, там можно легко конвертировать из одного в другой

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +.services-title {
Стили совпадают с селектором по классу .advantages-title, значит можно избежать дублирования и придумать название класса с более универсальным названием и его прописать обоим заголовкам, удалив старые названия

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +.services-title {
Таким образом вместо двух одинаковых селекторов останется один

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +.info-email
Лишний перенос строки

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    background-color: #000;
Цвет фона под фоновой картинке подбирается похожим на цвет самой картинки

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    text-align: center;
Лишнее свойство

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    text-align: center;
Лишние свойства

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    text-align: center;
Лишнее свойство

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    text-align: center;
в main-index ты уже написала text-align: center

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    text-transform: uppercase;
Лишние свойства

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    background-color: #000;
Цвет фона не совпадает с картинкой

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    font-weight: 700;
Лишнее свойство

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +    font-weight: 700;
Лишнее свойство

2022-10-28 11:24 UTC, maxzbest commented on styles/styles.css
> +.info-email-description-inner {
А зачем вообще дублировать эти стили? Там же такой же блок

2022-11-05 14:40 UTC, uk-ka commented on styles/styles.css
> + .button-email {
112 строчка

2022-11-05 14:52 UTC, uk-ka commented on styles/styles.css
> +.info-email-description-inner {
в каталоге нет фоновой картинки и текст черный

2022-11-05 14:54 UTC, uk-ka commented
поправила

2022-11-07 12:15 UTC, maxzbest commented on styles/styles.css
> +.info-email-description-inner {
Значит мы можем использовать дополнительный класс, который будет менять ТОЛЬКО фоновое изображения и цвет текста, нужно избегать дублирования

2022-11-07 12:15 UTC, maxzbest approved these changes

2022-11-07 12:15 UTC, merged